CI: Fix Cross installation failing (#3)
The latest version of one of the dependencies became incompatible with
the CI environment. The installation began failing with the following
error message:

  error: failed to compile `cross v0.2.5 (https://github.com/cross-rs/cross?rev=88f49ff79e777bef6d3564531636ee4d3cc2f8d2#88f49ff7)`, intermediate artifacts can be found at `/tmp/cargo-installqyrMjf`.
  To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

  Caused by:
    rustc 1.80.0 is not supported by the following package:
      home@0.5.11 requires rustc 1.81
    Either upgrade rustc or select compatible dependency versions with
    `cargo update <name>@<current-ver> --precise <compatible-ver>`
    where `<compatible-ver>` is the latest version supporting rustc 1.80.0